# import User from './User/User.gql'
# import Game from './Game/Game.gql'
# import Purchase from './Purchase/Purchase.gql'
# import DownloadKey from './DownloadKey/DownloadKey.gql'

type Query {
  # Returns information about the enabled API key/JWT's scopes
  info: [String]
  # Returns the profile of the authenticated user
  me: User
  # Returns the games of the authenticated user
  games: [Game]
  # Returns the purchases of a game for a given user/email
  purchases(game: Int!, userId: Int, email: String): [Purchase]
  # Returns a game's download key for a given user/email/key ID
  downloadKey(game: Int!, userId: Int, email: String, key: String): DownloadKey
}
